title: MATLAB LaMSA Model
logo: /docs/posmlab_logo.png
description: [Physics of Soft Matter Lab at Harvey Mudd College](https://posmlab.org)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
